language: sh
os: windows

before_install:
  - choco install python
  #- choco install pywin32
  - python -m pip install pyinstaller
install:
  - python -m pip install pywin32
  - python -m pip install -r requirements.txt

script:
  - cp config_sample.py config.py
  - pyinstaller --onefile --distpath c:\PythonBuild --noconsole --win-private-assemblies PasswordChange.py
